// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';
import { Default, type Options } from '../sdk.gen';
import type { CreateProxyPatternData, CreateProxyPatternError, CreateProxyPatternResponse, DeleteProxyPatternData, DeleteProxyPatternError, DeleteProxyPatternResponse, ListProxyPatternsData, ListProxyPatternsError, ListProxyPatternsResponse, ReadProxyPatternData, UpdateProxyPatternData, UpdateProxyPatternError, UpdateProxyPatternResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const listProxyPatternsQueryKey = (options?: Options<ListProxyPatternsData>) => createQueryKey('listProxyPatterns', options);

/**
 * List Proxy Patterns
 */
export const listProxyPatternsOptions = (options?: Options<ListProxyPatternsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Default.listProxyPatterns({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listProxyPatternsQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listProxyPatternsInfiniteQueryKey = (options?: Options<ListProxyPatternsData>): QueryKey<Options<ListProxyPatternsData>> => createQueryKey('listProxyPatterns', options, true);

/**
 * List Proxy Patterns
 */
export const listProxyPatternsInfiniteOptions = (options?: Options<ListProxyPatternsData>) => {
    return infiniteQueryOptions<ListProxyPatternsResponse, AxiosError<ListProxyPatternsError>, InfiniteData<ListProxyPatternsResponse>, QueryKey<Options<ListProxyPatternsData>>, number | Pick<QueryKey<Options<ListProxyPatternsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListProxyPatternsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await Default.listProxyPatterns({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listProxyPatternsInfiniteQueryKey(options)
    });
};

export const createProxyPatternQueryKey = (options: Options<CreateProxyPatternData>) => createQueryKey('createProxyPattern', options);

/**
 * Create Proxy Pattern
 */
export const createProxyPatternOptions = (options: Options<CreateProxyPatternData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Default.createProxyPattern({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createProxyPatternQueryKey(options)
    });
};

/**
 * Create Proxy Pattern
 */
export const createProxyPatternMutation = (options?: Partial<Options<CreateProxyPatternData>>): UseMutationOptions<CreateProxyPatternResponse, AxiosError<CreateProxyPatternError>, Options<CreateProxyPatternData>> => {
    const mutationOptions: UseMutationOptions<CreateProxyPatternResponse, AxiosError<CreateProxyPatternError>, Options<CreateProxyPatternData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await Default.createProxyPattern({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Proxy Pattern
 */
export const deleteProxyPatternMutation = (options?: Partial<Options<DeleteProxyPatternData>>): UseMutationOptions<DeleteProxyPatternResponse, AxiosError<DeleteProxyPatternError>, Options<DeleteProxyPatternData>> => {
    const mutationOptions: UseMutationOptions<DeleteProxyPatternResponse, AxiosError<DeleteProxyPatternError>, Options<DeleteProxyPatternData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await Default.deleteProxyPattern({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readProxyPatternQueryKey = (options: Options<ReadProxyPatternData>) => createQueryKey('readProxyPattern', options);

/**
 * Read Proxy Pattern
 */
export const readProxyPatternOptions = (options: Options<ReadProxyPatternData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Default.readProxyPattern({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readProxyPatternQueryKey(options)
    });
};

/**
 * Update Proxy Pattern
 */
export const updateProxyPatternMutation = (options?: Partial<Options<UpdateProxyPatternData>>): UseMutationOptions<UpdateProxyPatternResponse, AxiosError<UpdateProxyPatternError>, Options<UpdateProxyPatternData>> => {
    const mutationOptions: UseMutationOptions<UpdateProxyPatternResponse, AxiosError<UpdateProxyPatternError>, Options<UpdateProxyPatternData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await Default.updateProxyPattern({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
