// This file is auto-generated by @hey-api/openapi-ts

import type { CreateProxyPatternResponse, ListProxyPatternsResponse, ReadProxyPatternResponse, UpdateProxyPatternResponse } from './types.gen';

const proxyPatternReadSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const listProxyPatternsResponseTransformer = async (data: any): Promise<ListProxyPatternsResponse> => {
    data = data.map((item: any) => {
        return proxyPatternReadSchemaResponseTransformer(item);
    });
    return data;
};

export const createProxyPatternResponseTransformer = async (data: any): Promise<CreateProxyPatternResponse> => {
    data = proxyPatternReadSchemaResponseTransformer(data);
    return data;
};

export const readProxyPatternResponseTransformer = async (data: any): Promise<ReadProxyPatternResponse> => {
    data = proxyPatternReadSchemaResponseTransformer(data);
    return data;
};

export const updateProxyPatternResponseTransformer = async (data: any): Promise<UpdateProxyPatternResponse> => {
    data = proxyPatternReadSchemaResponseTransformer(data);
    return data;
};
