"""Add rls policies

Revision ID: a83fce0a6509
Revises: f98950563639
Create Date: 2025-12-01 09:56:15.136430

"""

from collections.abc import Sequence

from alembic import op
from alembic_utils.pg_extension import PGExtension
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_policy import PGPolicy

# revision identifiers, used by Alembic.
revision: str = "a83fce0a6509"
down_revision: str | None = "f98950563639"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tasks ENABLE ROW LEVEL SECURITY")

    public_set_current_user = PGFunction(
        schema="public",
        signature="set_current_user(user_id integer)",
        definition="RETURNS VOID AS $$\n    BEGIN\n        PERFORM set_config('app.current_user_id', user_id::text, false);\n    END;\n    $$ LANGUAGE plpgsql",
    )
    op.create_entity(public_set_current_user)

    public_get_current_user = PGFunction(
        schema="public",
        signature="get_current_user()",
        definition="RETURNS integer AS $$\n    DECLARE\n        user_id_text text;\n    BEGIN\n        user_id_text := current_setting('app.current_user_id', true);\n\n        -- Return NULL if not set or empty string\n        IF user_id_text IS NULL OR user_id_text = '' THEN\n            RETURN NULL;\n        END IF;\n\n        -- Try to convert to integer, return NULL if invalid\n        BEGIN\n            RETURN user_id_text::integer;\n        EXCEPTION WHEN invalid_text_representation THEN\n            RETURN NULL;\n        END;\n    END;\n    $$ LANGUAGE plpgsql",
    )
    op.create_entity(public_get_current_user)

    public_postgis = PGExtension(schema="public", signature="postgis")
    op.create_entity(public_postgis)

    public_tasks_tasks_user_policy = PGPolicy(
        schema="public",
        signature="tasks_user_policy",
        on_entity="public.tasks",
        definition="AS PERMISSIVE\n    USING (EXISTS (\n        SELECT 1\n        FROM app_users ua\n        WHERE ua.id = get_current_user() AND ua.id = tasks.creator_id\n    ))",
    )
    op.create_entity(public_tasks_tasks_user_policy)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_tasks_tasks_user_policy = PGPolicy(
        schema="public",
        signature="tasks_user_policy",
        on_entity="public.tasks",
        definition="AS PERMISSIVE\n    USING (EXISTS (\n        SELECT 1\n        FROM app_users ua\n        WHERE ua.id = get_current_user() AND ua.id = tasks.creator_id\n    ))",
    )
    op.drop_entity(public_tasks_tasks_user_policy)

    public_postgis = PGExtension(schema="public", signature="postgis")
    op.drop_entity(public_postgis)

    public_get_current_user = PGFunction(
        schema="public",
        signature="get_current_user()",
        definition="RETURNS integer AS $$\n    DECLARE\n        user_id_text text;\n    BEGIN\n        user_id_text := current_setting('app.current_user_id', true);\n\n        -- Return NULL if not set or empty string\n        IF user_id_text IS NULL OR user_id_text = '' THEN\n            RETURN NULL;\n        END IF;\n\n        -- Try to convert to integer, return NULL if invalid\n        BEGIN\n            RETURN user_id_text::integer;\n        EXCEPTION WHEN invalid_text_representation THEN\n            RETURN NULL;\n        END;\n    END;\n    $$ LANGUAGE plpgsql",
    )
    op.drop_entity(public_get_current_user)

    public_set_current_user = PGFunction(
        schema="public",
        signature="set_current_user(user_id integer)",
        definition="RETURNS VOID AS $$\n    BEGIN\n        PERFORM set_config('app.current_user_id', user_id::text, false);\n    END;\n    $$ LANGUAGE plpgsql",
    )
    op.drop_entity(public_set_current_user)

    op.execute("ALTER TABLE tasks DISABLE ROW LEVEL SECURITY")

    # ### end Alembic commands ###
