"""Add user table and relation

Revision ID: f98950563639
Revises: 55821e91e400
Create Date: 2025-12-01 09:55:03.065340

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f98950563639"
down_revision: str | None = "55821e91e400"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("auth0_sub", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth0_sub"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_app_users_created_at"), "app_users", ["created_at"], unique=False
    )
    op.add_column("tasks", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tasks", "app_users", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "creator_id")
    op.drop_index(op.f("ix_app_users_created_at"), table_name="app_users")
    op.drop_table("app_users")
    # ### end Alembic commands ###
